# Generated by Django 6.0.3 on 2026-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='timestep',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
