# Generated by Django 6.0.3 on 2026-05-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_pagevisit_timestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
